[package]
name = "gkrust"
version = "0.1.0"
authors = ["nobody@mozilla.org"]
license = "MPL-2.0"
description = "Rust code for libxul"

[dependencies]
mp4parse = { path = "../../../media/libstagefright/binding/mp4parse" }
nsstring = { path = "../../../xpcom/rust/nsstring" }

[lib]
path = "lib.rs"
test = false
doctest = false
bench = false
doc = false
plugin = false
harness = false
