[package]
name = "gkrust"
version = "0.1.0"
authors = ["nobody@mozilla.org"]
license = "MPL-2.0"
description = "Rust code for libxul"

[dependencies]
mp4parse = { path = "../../../media/libstagefright/binding/mp4parse" }
nsstring = { path = "../../../xpcom/rust/nsstring" }

# We include all gtest code alongside our non-gtest code. The linker should
# throw out these unused symbols when linking libxul normally, and this means
# that we always have exactly 1 rust library in tree, which avoids a ton of
# problems related to linking multiple rust-created staticlibs into a single
# library.
gkrust-gtest = { path = "../gtest/rust" }

[lib]
path = "lib.rs"
crate-type = ["staticlib"]
test = false
doctest = false
bench = false
doc = false
plugin = false
harness = false

# Explicitly specify what our profiles use.
[profile.dev]
opt-level = 1
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 1
panic = "abort"

[profile.release]
opt-level = 2
debug = true
rpath = false
lto = true
debug-assertions = false
panic = "abort"
